resources:
  containers:
    - container: ubuntu_x64_build_container
      image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-c103199-20180628134544

# CI Trigger on master branch
trigger:
  branches:
    include:
    - master
  paths:
    exclude: # don't trigger the CI if only a doc file was changed
    - docs/*
    - eng/common/README.md
    - src/benchmarks/micro/Serializers/README.md
    - src/benchmarks/micro/README.md
    - src/benchmarks/real-world/JitBench/README.md
    - src/benchmarks/real-world/Microsoft.ML.Benchmarks/Input/README.md
    - src/tools/ResultsComparer/README.md
    - README.md

# Trigger builds for PR's targeting master
pr:
  branches:
    include:
    - master
  paths:
    exclude: # don't trigger the CI if only a doc file was changed
    - docs/*
    - eng/common/README.md
    - src/benchmarks/micro/Serializers/README.md
    - src/benchmarks/micro/README.md
    - src/benchmarks/real-world/JitBench/README.md
    - src/benchmarks/real-world/Microsoft.ML.Benchmarks/Input/README.md
    - src/tools/ResultsComparer/README.md
    - README.md

jobs:

# Windows 10 x64 micro benchmarks
- template: /eng/common/templates/job/performance.yml	
  parameters:	
    jobName: windows_10_x64_micro
    displayName: Windows 10 x64 micro
    extraSetupParameters: -Architecture x64
    pool: 
      name: Hosted VS2017
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      frameworks: # for public jobs we want to make sure that the PRs don't break any of the supported frameworks	
        - netcoreapp3.0  
        - netcoreapp2.2
        - netcoreapp2.1
        - net461
    ${{ if ne(variables['System.TeamProject'], 'public') }}:
      frameworks: 
        - netcoreapp3.0

# Windows 10 x86 micro benchmarks
- template: /eng/common/templates/job/performance.yml	
  parameters:	
    jobName: windows_10_x86_micro
    displayName: Windows 10 x86 micro
    extraSetupParameters: -Architecture x86
    pool: 
      name: Hosted VS2017
    frameworks: 
      - netcoreapp3.0

# Ubuntu 1804 x64 micro benchmarks		
- template: /eng/common/templates/job/performance.yml	
  parameters:	
    jobName: ubuntu_1804_x64_micro
    displayName: Ubuntu 1804 x64 micro
    pool:
      name: Hosted Ubuntu 1604	
    container: ubuntu_x64_build_container
    extraSetupParameters: --architecture x64
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      frameworks: # for public jobs we want to make sure that the PRs don't break any of the supported frameworks	
        - netcoreapp3.0  
        - netcoreapp2.2
        - netcoreapp2.1
    ${{ if ne(variables['System.TeamProject'], 'public') }}:
      frameworks: 
        - netcoreapp3.0
        
# Ubuntu 1804 ARM64 micro benchmarks, private job
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/job/performance.yml	
    parameters:	
      jobName: ubuntu_1804_arm64_micro
      displayName: Ubuntu 1804 arm64 micro
      pool:
        name: Hosted Ubuntu 1604	
      container: ubuntu_x64_build_container
      extraSetupParameters: --architecture arm64
      frameworks: 
        - netcoreapp3.0

# Windows x64 ML.NET benchmarks
- template: /eng/common/templates/job/performance.yml	
  parameters:	
    jobName: windows_10_x64_mldotnet
    displayName: Windows 10 x64 mldotnet
    extraSetupParameters: -Architecture x64 -Csproj src\benchmarks\real-world\Microsoft.ML.Benchmarks\Microsoft.ML.Benchmarks.csproj -Kind mlnet -RunCategories mldotnet
    pool: 
      name: Hosted VS2017
    frameworks:
      - netcoreapp3.0  

# Ubuntu 1804 x64 ML.NET benchmarks
- template: /eng/common/templates/job/performance.yml	
  parameters:	
    jobName: ubuntu_1804_x64_mldotnet
    displayName: Ubuntu 1804 x64 mldotnet
    pool:
      name: Hosted Ubuntu 1604	
    container: ubuntu_x64_build_container
    extraSetupParameters: --architecture x64 --csproj src/benchmarks/real-world/Microsoft.ML.Benchmarks/Microsoft.ML.Benchmarks.csproj --kind mlnet --runcategories mldotnet
    frameworks: 
      - netcoreapp3.0

# Windows x64 Roslyn benchmarks
- template: /eng/common/templates/job/performance.yml	
  parameters:	
    jobName: windows_10_x64_roslyn
    displayName: Windows 10 x64 roslyn
    extraSetupParameters: -Architecture x64 -Csproj src\benchmarks\real-world\Roslyn\CompilerBenchmarks.csproj -Kind roslyn -RunCategories roslyn
    pool: 
      name: Hosted VS2017
    frameworks:
      - netcoreapp3.0 

# Ubuntu 1804 x64 Roslyn benchmarks
- template: /eng/common/templates/job/performance.yml	
  parameters:	
    jobName: ubuntu_1804_x64_roslyn
    displayName: Ubuntu 1804 x64 roslyn
    pool:
      name: Hosted Ubuntu 1604	
    container: ubuntu_x64_build_container
    extraSetupParameters: --architecture x64 --csproj src/benchmarks/real-world/Roslyn/CompilerBenchmarks.csproj --kind roslyn --runcategories roslyn
    frameworks: 
      - netcoreapp3.0
        