resources:
  containers:
    - container: ubuntu_x64_build_container
      image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-c103199-20180628134544

# CI Trigger on master branch
trigger:
  branches:
    include:
    - master
  paths:
    exclude: # don't trigger the CI if only a doc file was changed
    - docs/*
    - eng/common/README.md
    - src/benchmarks/micro/Serializers/README.md
    - src/benchmarks/micro/README.md
    - src/benchmarks/real-world/JitBench/README.md
    - src/benchmarks/real-world/Microsoft.ML.Benchmarks/Input/README.md
    - src/tools/ResultsComparer/README.md
    - README.md

# Trigger builds for PR's targeting master
pr:
  branches:
    include:
    - master
  paths:
    exclude: # don't trigger the CI if only a doc file was changed
    - docs/*
    - eng/common/README.md
    - src/benchmarks/micro/Serializers/README.md
    - src/benchmarks/micro/README.md
    - src/benchmarks/real-world/JitBench/README.md
    - src/benchmarks/real-world/Microsoft.ML.Benchmarks/Input/README.md
    - src/tools/ResultsComparer/README.md
    - README.md

schedules:
- cron: "0 */4 * * *"
  displayName: Every 4 hour build
  branches:
    include:
    - master
  always: true

jobs:

- template: /eng/common/templates/job/performance.yml	
  parameters:
    jobName: windows_RS5_x64_micro_compare
    displayName: windows RS5 x64 micro compare
    extraSetupParameters: -Architecture x64 -Compare
    pool:
      name: Hosted VS2017
    frameworks:
      - netcoreapp3.0

- template: /eng/common/templates/job/performance.yml	
  parameters:
    jobName: ubuntu_1804_x64_micro_compare
    displayName: ubuntu RS5 x64 micro compare
    extraSetupParameters: --architecture x64 --compare
    pool:
      name: Hosted Ubuntu 1604
    container: ubuntu_x64_build_container
    frameworks:
      - netcoreapp3.0
